### PR TITLE
Adding argument for freezing vision backbone.

### PR DESCRIPTION
**Pull request by 2U1**
Unfreezing the vision backbone while fine-tuning could be helpful for when finetuning according to the following tech report.
https://arxiv.org/pdf/2403.06199

### CODE REVIEW

**Comment by GaiZhenbiao** [comment]
It would be better if freezing the vision backbone were the default option.

**Comment by 2U1** [comment]
I thought it could be better for the adding --freeze_vision at the train.sh can be easier to see the option for users using this repo.

I've added the freeze_vision option at the train.sh

**Comment by GaiZhenbiao** [comment]
The lora modules are not added to the vision tower anyway though, unfreezing the vision tower will have no effect.

**Comment by 2U1** [comment]
Will implement the settings a bit later, thanks

**Pull request closed without merging**
